# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=100)),
                ('applicant', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=30)),
                ('apply_org', models.CharField(max_length=50)),
                ('char_num', models.IntegerField(default=0)),
                ('desk_num', models.IntegerField(default=0)),
                ('tent_num', models.IntegerField(default=0)),
                ('umbrella_num', models.IntegerField(default=0)),
                ('red_num', models.IntegerField(default=0)),
                ('cloth_num', models.IntegerField(default=0)),
                ('loud_num', models.IntegerField(default=0)),
                ('sound_num', models.IntegerField(default=0)),
                ('projector', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('part', models.IntegerField(default=0)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mng.Apply')),
            ],
        ),
    ]
