# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0003_kv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applytime',
            name='apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='mng.Apply'),
        ),
    ]
