# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0004_auto_20160222_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applytime',
            name='apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rap', to='mng.Apply'),
        ),
    ]
