# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0006_auto_20160229_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='record_day',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='record_month',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='record_year',
        ),
    ]
